#!/usr/bin/env bash
chsh -s $(which fish)
eval "$(grep -vFx '[ -z "$PS1" ] && return' /root/.bashrc)"
. /root/.bashrc
cargo install ripgrep
cargo install bat
fnm install 18
fnm use 18
npm install -g neovim
./install
rm -rf /home/root
ln -s /root /home/root
bat cache -b
fish
