require('settings.devicons');
require('settings.gitsigns');
require('settings.telescope');
require('settings.lualine');
require('settings.nvim-autopairs');
require('settings.nvim-treesitter');
require('settings.hop');
require('settings.project');
require('settings.nvimtree');
